- platform: mqtt
  state_topic: "stat/sonoff-lounge-sensor/POWER"
  name: Lounge Sonoff PIR
  device_class: motion
  payload_on: "ON"
  payload_off: "OFF"
  
- platform: mqtt
  state_topic: "stat/sonoff-bedroom-sensor/POWER"
  name: Bedroom Sonoff PIR
  device_class: motion
  payload_on: "ON"
  payload_off: "OFF"