## Lightning
- id: evening_lights_on
  alias: Evening Lights On
  initial_state: 'on'
  trigger:
  - at: '20:01:00'
    platform: time
  action:
  - data:
      brightness: 255
      entity_id: light.lounge_lamp
    service: light.turn_on
    
- id: all_lights_off
  alias: Lights Out after bed
  initial_state: 'on'
  trigger:
  - at: '00:31:00'
    platform: time
  action:
  - data:
      entity_id: light.lounge_lamp
    service: light.turn_off
    
- id: away_mode
  alias: Away Mode
  initial_state: 'on'
  trigger:
  - entity_id: device_tracker.rich_s8
    platform: state
    to: not_home
  action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off

    
- id: bedroom_motion_lights
  alias: Motion Lights Bedroom
  initial_state: 'on'
  trigger:
  - entity_id: sensor.bedroom_sensor_node_pir
    from: standby
    platform: state
    to: motion detected
  action:
  - data:
      entity_id: light.bedroom_light
    service: light.turn_on

## Home Assistant based
- id: update_available_notification
  alias: Update Available Notification
  initial_state: 'on'
  trigger:
    platform: template
    value_template: '{{states.sensor.pypi_hass_version.state == states.sensor.current_version.state}}'
  action:
  - service: notify.pushbullet
    data:
      message: HomeAssistant {{ states('states.sensor.pypi_hass_version.state') }}
        is now available
      title: Update HASS
  - service: persistent_notification.create
    data:
      title: Update Available
      message: 'Home Assistant {{ states(''states.sensor.pypi_hass_version.state'')
        }} is available, please update.

        '
      notification_id: update_available
