homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/London
  customize: !include_dir_merge_named customize
  customize_glob: !include customize-glob.yaml
  whitelist_external_dirs:
    - /home/homeassistant/.homeassistant/

http:
  api_password: !secret http_password
  #ssl_certificate: !secret ssl_certificate
  #ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 5
  
custom_updater:
  track:
    - cards
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home_assistant1
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  discovery_prefix: homeassistant
  
camera:
  - platform: rpi_camera
    name: Lounge Camera
    image_quality: 80
    
#  - platform: mjpeg
#    mjpeg_url: http://192.168.0.196:8081

weather:
  - platform: darksky
    api_key: !secret dark_sky_api
    latitude: !secret latitude
    longitude: !secret longitude
    mode: daily
    
system_health:
config:
sun:
updater:
conversation:
lovelace:
  mode: yaml
discovery:
  ignore:
    - igd

logger:
  default: error
  logs:
    homeassistant.components.mqtt: warn

tts:
  - platform: google

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api

panel_iframe:
  plex_server:
    title: 'Plex'
    url: 'http://192.168.0.237:32400/web'
    
    
####################################################
#                                                  #
#                     Includes #
#                                                  #
#####################################################
device_tracker: !include_dir_merge_list device_tracker
weblink: !include weblink.yaml
media_player: !include_dir_merge_list media_player
light: !include_dir_merge_list light
sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
group: !include_dir_merge_named group
automation: !include_dir_merge_list automation
frontend: !include frontend.yaml
logbook: !include logbook.yaml
recorder: !include recorder.yaml
history: !include history.yaml
switch: !include_dir_merge_list switch
input_select: !include_dir_merge_named input_select
shell_command: !include_dir_merge_named shell_command
script: !include_dir_merge_named script
alarm_control_panel: !include_dir_merge_list alarm_cp

