resources:
  - url: /customcards/mini-media-player-bundle.js
    type: module
  - url: /customcards/tracker-card.js
    type: js
  - url: /customcards/gauge-card.js
    type: js
  - url: /customcards/slider-entity-row.js
    type: js
  - url: /customcards/button-card.js
    type: module
  - url: /customcards/group-card.js
    type: js
  - url: /customcards/compact-custom-header.js
    type: module
  - url: /customcards/fold-entity-row.js
    type: js
  - url: /customcards/card-tools.js
    type: js
  - url: /customcards/weather-card.js
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.3.0
    type: module

title: Home
#background: fill / cover no-repeat url("/local/lovelace/light-clean-bg.jpg") fixed
#background: var--(background)
views:

## HOME VIEW #######

  - title: Home
    panel: false
    icon: mdi:home
    background: var--(background)
    cards:
      - type: custom:compact-custom-header
        main_config: true
        menu: hide
        options: clock
        voice: overflow
        notifications: overflow
        header: true
        clock_format: 24
        clock_am_pm: false
      - type: glance
        column_width: calc(100% / 3)
        show_name: false
        title: Lounge
        entities:
          - entity: sensor.lounge_temperature
            icon: mdi:thermometer
          - entity: sensor.lounge_humidity
            icon: mdi:water-percent
          - entity: binary_sensor.lounge_sonoff_pir

      - type: horizontal-stack
        cards:
          - type: light
            entity: light.lounge_lamp
          - type: light
            entity: light.bridge
            name: Bookshelf
         
      - type: glance
        column_width: calc(100% / 3)
        show_name: false
        title: Bedroom
        entities:
          - entity: sensor.bedroom_temperature
            icon: mdi:thermometer
          - entity: sensor.bedroom_humidity
            icon: mdi:water-percent
          - entity: binary_sensor.bedroom_sonoff_pir
            
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.bedroom_light
            name: Main Light
          - type: light
            entity: light.bedside_lampsonoff_mqtt
            name: Bedside Lamp
            
      - type: light
        entity: light.kitchen_cupboard_lights
        name: Kitchen Unit
        
## MEDIA VIEW #######

  - title: Media
    panel: false
    icon: mdi:television
    background: var--(background)
    cards:
      - type: custom:compact-custom-header

      - type: horizontal-stack
        cards:
          - type: glance
            title: Lounge
            show_name: false
            entities:
              - entity: sensor.av_temps_temperature
              - entity: sensor.av_temps_humidity
          - type: glance
            show_name: false
            title: Play Time
            entities:
              - entity: sensor.tv_watched_daily
                icon: mdi:television
              - entity: sensor.xbox_played_daily
                icon: mdi:xbox

      - type: vertical-stack
        cards:
          - type: "custom:mini-media-player"
            entity: media_player.bravia_tv
            icon: mdi:television
            artwork: full-cover
            show_source: true
            hide:
              volume: true
              controls: true
              power_state: false
          - type: picture-glance
            title: Harmony
            entities:
              - switch.watch_tv
              - switch.watch_netflix
              - switch.xbox_one
            state_image:
              "PowerOff": /local/lovelace/harmony/power_off_red.png
              "Play Xbox One": /local/lovelace/harmony/xbox_one_logo.png
              "Watch TV": /local/lovelace/harmony/television_logo.jpg
              "Watch Netflix": /local/lovelace/harmony/netflix_logo.png
            entity: sensor.harmony_activity
          - type: conditional
            conditions:
              - entity: sensor.valiceemo
                state: "Online"
            card:
              type: entities
              entities:
                - sensor.valiceemo
                - sensor.xbox_valiceemo_currently_playing
                - sensor.xbox_valiceemo_gamerscore


      - type: custom:mini-media-player
        entity: media_player.lounge_google_home
        icon: mdi:google-home
        artwork: full-cover
        volume_stateless: false
        show_progress: false
        show_source: true
      - type: conditional
        conditions:
          - entity: media_player.living_room_chromecast
            state: "playing"
        card:
          type: custom:mini-media-player
          entity: media_player.living_room_chromecast
          icon: mdi:google-home
          artwork: full-cover
          volume_stateless: false
          show_progress: false
          show_source: true
          
      - type: conditional
        conditions:
          - entity: media_player.bedroom_google_home
            state: "playing"
        card:
          type: custom:mini-media-player
          entity: media_player.bedroom_google_home
          icon: mdi:google-home
          artwork: full-cover
          volume_stateless: false
          show_source: true
          hide:
            volume: false
            controls: false
            power_state: false
            progress: true
        

## SECURITY VIEW ##

  - title: Security
    panel: false
    icon: mdi:cctv
    background: var--(background)
    cards:
      - type: custom:compact-custom-header
      - type: picture-entity
        entity: camera.lounge_camera
        
      - type: alarm-panel
        entity: alarm_control_panel.ha_manual_alarm

## WEATHER VIEW ##

  - title: Weather
    panel: false
    icon: mdi:weather-cloudy
    background: var--(background)
    cards:
      - type: custom:compact-custom-header
      
      - type: custom:weather-card
        entity: weather.dark_sky
        icons: "/local/icons/weather_icons/animated/"
      

## AUTOMATIONS TEST VIEW ##

  - title: Automations TEST
    icon: mdi:home-automation
    background: var--(background)
    cards:
      - type: custom:compact-custom-header
      - type: entities
        title: Automations
        show_header_toggle: false
        entities: 
          - type: custom:fold-entity-row
            head: 
              type: section
              label: Lighting
            items:
              - automation.evening_lights_on
              - automation.motion_lights_lounge_full
              - automation.motion_lights_bedroom_full
              - automation.lounge_lamp_off_after_10
              - automation.bedroom_lights_off_after_10
              - automation.lounge_lamp_off_sun_up
              - automation.turn_all_lights_off_at_night
              - automation.turn_all_lights_off_when_away
              - automation.turn_all_lights_on_when_returning

          - type: custom:fold-entity-row
            head: 
              type: section
              label: Presence
            items:
              - automation.presence_detection

          - type: custom:fold-entity-row
            head: 
              type: section
              label: System
            items:
              - automation.ha_update_available
              - automation.home_assistant_started_notify
              - automation.login_failure
              - automation.set_theme
              - automation.network_device_notifier
              - automation.clear_tts_cache

          - type: custom:fold-entity-row
            head: 
              type: section
              label: Home Modes
            items:
              - automation.home_mode_home
              - automation.home_mode_away
              - automation.home_mode_morning_weekend
              - automation.home_mode_workday
              - automation.home_mode_night
              - automation.intruder
              
      - type: entities
        title: Scripts
        show_header_toggle: false
        entities: 
          - type: custom:fold-entity-row
            head: group.all_scripts

## NETWORK

  - title: Network
    icon: mdi:router-wireless
    background: var--(background)
    cards:
      - type: custom:compact-custom-header
      - type: glance
        title: Network Speeds
        column_width: calc(100% / 3)
        show_name: false
        entities:
          - entity: sensor.speedtest_download
            name: Download
            icon: mdi:download
          - entity: sensor.speedtest_upload
            name: Upload
            icon: mdi:upload
          - entity: sensor.speedtest_ping
            name: Ping
            icon: mdi:speedometer
            hold_action: call-service
            service: sensor.update_speedtest
            
      - type: entities
        entities:
          - entity: sensor.external_ip
            name: External IP
            icon: mdi:ip-network
          - entity: sensor.ipv4_address_eth0
            name: Local IP
            icon: mdi:ip-network

      - type: entities
        title: Pi-Hole
        show_header_toggle: false
        entities:
          - entity: binary_sensor.device_tracker_rpi_pihole
            name: Status
          - entity: sensor.pi_hole_domains_blocked
            name: Total Domains Being Blocked
          - entity: sensor.pi_hole_dns_queries_today
            name: DNS Queries Today
          - entity: sensor.pi_hole_ads_blocked_today
            name: Queries Blocked Today
          - entity: sensor.pi_hole_ads_percentage_blocked_today
            name: Percentage Blocked Today
          - type: divider
          - entity: sensor.pi_hole_cpu_temp
            name: CPU Temp
            icon: mdi:thermometer
          - entity: sensor.pi_hole_cpu_usage
            name: CPU Usage
            icon: mdi:memory
          - entity: sensor.pi_hole_boot_time
            name: Last Booted
            icon: mdi:update
          - entity: sensor.pi_hole_disk_usage
            name: Disk Usage
            icon: mdi:micro-sd
          - type: divider
          - type: weblink
            name: Pi-Hole
            url: http://pi.hole/admin
            icon: mdi:raspberrypi
          - type: divider
          - type: weblink
            name: Sky Hub
            url: http://192.168.0.1
            icon: mdi:router-wireless

      - type: entities
        title: Device Status
        show_header_toggle: false
        entities:
          - entity: binary_sensor.device_tracker_sony_braviatv
            name: Lounge Sony TV
          - entity: binary_sensor.device_tracker_skyhd
            name: Sky+
          - entity: binary_sensor.device_tracker_harmony_hub
            name: Lounge Harmony Hub
          - entity: binary_sensor.device_tracker_chromecast_lounge
            name: Lounge Chromecast
          - entity: binary_sensor.device_tracker_google_home_lounge
            name: Lounge Google Home
          - entity: binary_sensor.device_tracker_xbox_one
            name: Xbox
          - entity: binary_sensor.device_tracker_sonoff_nodemcu_sensor_lounge
            name: Lounge Sensor Node
          - type: divider
          - entity: binary_sensor.device_tracker_chromecast_bedroom
            name: Bedroom Chromecast
          - entity: binary_sensor.device_tracker_google_home_bedroom
            name: Bedroom Google Home
          - entity: binary_sensor.device_tracker_sonoff_nodemcu_sensor_bedroom
            name: Bedroom Sensor Node
          - entity: binary_sensor.device_tracker_sonoff1_bedside_lamp
            name: Sonoff1 - Bedside Lamp 
          - type: divider
          - entity: binary_sensor.device_tracker_milight_bridge
            name: Mi-Light
          - entity: binary_sensor.device_tracker_rich_laptop
            name: Rich Laptop
          - entity: binary_sensor.device_tracker_gear_watch
            name: Rich S2 Watch
          - entity: binary_sensor.device_tracker_lenovo_tab
            name: Rich Tablet

## SYSTEM VIEW ##

  - title: System
    panel: false
    icon: mdi:settings
    background: var--(background)
    cards:
      - type: custom:compact-custom-header
      - type: horizontal-stack
        cards:
          - type: gauge
            entity: sensor.hassbian_cpu_temp
            name: CPU Temp
          - type: gauge
            entity: sensor.processor_use
            name: CPU Use
          - type: gauge
            entity: sensor.memory_use_percent
            name: Memory Use
      - type: entities
        title: System
        show_header_toggle: false
        entities:
          - entity: sensor.ha_time_online
            name: HA Uptime
            icon: mdi:update
          - entity: sensor.hassbian_boot_time
            name: Hassbian Last Boot
            icon: mdi:update
          - entity: sensor.home_assistant_v2_db
            name: Database Size
          - entity: sensor.disk_free_home
            name: Free SD space
          - entity: sensor.ha_installed_version
            name: HA Version
          - type: divider
          - entity: input_select.theme_changer
            name: Theme select
          - entity: script.reload_themes
            name: Reload Themes
            icon: mdi:reload
          - type: divider
          - type: weblink
            name: Home Assistant
            url: https://www.home-assistant.io
            icon: mdi:home-assistant
             
      - type: custom:tracker-card
        title: Card Updates
        
