resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.8
    type: module
  - url: /local/custom_ui/weather-card.js
    type: js
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  - url: /local/gauge-card.js?v=0.2.0
    type: js
  - url: /local/slider-entity-row.js?v=d6da75
    type: js
  - url: /local/button-card.js
    type: module
  - url: /local/group-card.js
    type: js
  - url: /local/bignumber-card.js
    type: js
  - url: /local/useful-markdown-card.js
    type: js
  - url: /local/dark-sky-weather-card.js?v=4
    type: js

title: Home
background: radial-gradient(white, skyblue)
views:

## HOME VIEW #######

  - title: Home
    panel: false
    icon: mdi:home
    
    cards:
      - type: glance
        column_width: calc(100% / 5)
        show_name: false
        title: Lounge
        entities:
          - entity: sensor.lounge_temperature
            icon: mdi:thermometer
          - entity: sensor.lounge_humidity
            icon: mdi:water-percent
          - entity: binary_sensor.lounge_sensor_motion2
          - entity: sensor.lounge_light_level
          ##
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.lounge_lamp
          - type: light
            entity: light.bridge
         
      - type: glance
        column_width: calc(100% / 4)
        show_name: false
        title: Bedroom
        entities:
          - entity: sensor.bedroom_temperature
            icon: mdi:thermometer
          - entity: sensor.bedroom_humidity
            icon: mdi:water-percent
          - entity: binary_sensor.bedroom_sensor_motion2
          - entity: sensor.master_bedroom_light_level
            
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            color_type: icon
            entity: light.bedroom_light
            action: toggle
            name: Main Light
            icon: mdi:floor-lamp
            #color: rgb(255, 131, 0)
          - type: custom:button-card
            entity: switch.bedside_lamp
            name: Bedside Lamp
            #color: rgb(255, 255, 0)
            action: toggle
            icon: mdi:lamp
            #size: 82%
            color_type: icon
            color: rgb(255, 208, 0)
            

      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            color_type: blank-card
          - type: light
            entity: light.kitchen_cupboard_lights
            name: Poo
          - type: "custom:button-card"
            color_type: blank-card
            
## SECURITY VIEW ##

  - title: Security
    panel: true
    icon: mdi:water-percent
    
    cards:

      - type: picture-entity
        entity: camera.lounge_camera

## SECURITY VIEW ##

  - title: poo
    panel: false
    
    cards:
      - type: vertical-stack
        cards: 
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                color_type: card
                entity: light.lounge_lamp
                action: toggle
                name: Lounge Lamp
                icon: mdi:floor-lamp
                color: rgb(255, 131, 0)
              - type: custom:button-card
                color_type: card
                entity: light.bridge
                action: toggle
                name: Bookshelf
                icon: mdi:floor-lamp
                color: rgb(255, 131, 0)
          - type: horizontal-stack
            cards:
              - type: custom:bignumber-card
                entity: sensor.lounge_temperature
                scale: 30px
              - type: custom:bignumber-card
                entity: sensor.lounge_humidity
                scale: 30px
                icon: mdi:water-percent
                