resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.7
    type: module
  - url: /local/custom_ui/weather-card.js
    type: js
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  - url: /local/gauge-card.js?v=0.2.0
    type: js
  - url: /local/card-modder.js
    type: js
  - url: /local/button-card.js
    type: module
  - url: /local/group-card.js
    type: js
  - url: /local/bignumber-card.js
    type: js
  - url: /local/useful-markdown-card.js
    type: js
  - url: /local/dark-sky-weather-card.js?v=4
    type: js

title: Home
views:

## HOME VIEW ####

  - title: Home
    panel: false
#    background: center / cover no-repeat url("/local/lovelace/background-15.gif") fixed
    cards:

      - type: vertical-stack
        cards:
          - type: custom:button-card
            color_type: blank-card
          - type: custom:card-modder
            style:
              background-color: rgb(241, 196, 15)
              color: rgb(255, 255, 255)
              border-radius: 10px
              border: solid 1px rgba(100,100,100,0.3)
              #box-shadow: 3px 3px rgba(255,255,255,255)
            card:
              type: custom:useful-markdown-card 
              content: >
                SECURITY MODE: 
                [[ input_select.home_mode.state ]]
          - type: horizontal-stack
            cards:
              - type: custom:card-modder
                style:
                  background-color: rgb(241, 196, 15)
                  color: rgb(255, 255, 255)
                  border-radius: 10px
                  border: solid 1px rgba(100,100,100,0.3)
                  #box-shadow: 3px 3px rgba(255,255,255,255)
                card: 
                  type: custom:button-card
                  color_type: card
                  color: rgb(241, 196, 15)
                  color_off: rgb(255, 0, 25)
                  name: Home
                  action: service
                  service: 
                    domain: input_select
                    action: select_option
                    data: 
                      entity_id: input_select.home_mode
                      option: Home
              - type: "custom:button-card"
                color_type: card
                color: rgb(241, 196, 15)
                name: Away
                action: service
                service: 
                  domain: input_select
                  action: select_option
                  data: 
                    entity_id: input_select.home_mode
                    option: Away
              - type: "custom:button-card"
                color_type: card
                color: rgb(241, 196, 15)
                name: Night
                action: service
                service: 
                  domain: input_select
                  action: select_option
                  data: 
                    entity_id: input_select.home_mode
                    option: Night
              - type: "custom:button-card"
                color_type: card
                color: rgb(241, 196, 15)
                name: Vacation
                action: service
                service: 
                  domain: input_select
                  action: select_option
                  data: 
                    entity_id: input_select.home_mode
                    option: Vacation
          - type: "custom:button-card"
            color_type: blank-card

                
      - type: entities
        entities:
          - entity: sensor.tv_watched_daily
            icon: mdi:television
          - entity: sensor.tv_watched_weekly
                
      - type: entities
        title: System
        show_header_toggle: true
        entities:
          - entity: input_select.home_mode
            name: Home Mode
            icon: mdi:home
          
      - type: entity-filter
        entities: 
          - device_tracker.rich_phone_s8
        state_filter:
          - home
        show_empty: false
        card:
          type: glance
          title: People at home
          
          
      - type: entity-filter
        entities: 
          - light.lounge_lamp
          - light.bridge
          - light.bedroom_light
        state_filter:
          - on
        show_empty: false
        card:
          type: glance
          show_state: false
          title: Lights Left On
          
      - type: entity-filter
        entities:
          - entity: media_player.living_room_chromecast
            name: Lounge Chromecast
        show_empty: false
        state_filter: 
          - "on"
      - type: entity-filter
        entities:
          - entity: media_player.lounge_google_home
        state_filter:
          - "on"
        show_empty: false
      - type: entity-filter
        entities:
          - entity: media_player.bravia_tv
            name: Lounge TV
        state_filter:
          - on
        show_empty: false
        card:
          type: custom:mini-media-player
          entity: media_player.bravia_tv
          icon: mdi:router-wireless
          artwork_border: true
          show_source: true
          hide_volume: true
          hide_controls: true
          
      - type: map
        entities: 
          - device_tracker.rich_phone_s8
       
      - type: custom:dark-sky-weather-card
        entity_sun: sun.sun
        entity_daily_summary: sensor.dark_sky_daily_summary
        entity_current_conditions: sensor.dark_sky_icon
        entity_humidity: sensor.dark_sky_humidity
        entity_pressure: sensor.dark_sky_pressure
        entity_temperature: sensor.dark_sky_temperature
        entity_visibility: sensor.dark_sky_visibility
        entity_wind_bearing: sensor.dark_sky_wind_bearing
        entity_wind_speed: sensor.dark_sky_wind_speed
        entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1
        entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2
        entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3
        entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4
        entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5
        entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_1
        entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_2
        entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_3
        entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_4
        entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_5
        entity_forecast_icon_1: sensor.dark_sky_icon_1
        entity_forecast_icon_2: sensor.dark_sky_icon_2
        entity_forecast_icon_3: sensor.dark_sky_icon_3
        entity_forecast_icon_4: sensor.dark_sky_icon_4
        entity_forecast_icon_5: sensor.dark_sky_icon_5
        entity_summary_1: sensor.dark_sky_summary_1
        entity_summary_2: sensor.dark_sky_summary_2
        entity_summary_3: sensor.dark_sky_summary_3
        entity_summary_4: sensor.dark_sky_summary_4
        entity_summary_5: sensor.dark_sky_summary_5
      
      - type: custom:tracker-card
#        title: Tracker poo
        trackers: 
          - sensor.custom_card_tracker


## LIVING ROOM VIEW ##

  - title: Living Room
    cards:
      - type: picture-entity
        entity: camera.lounge_camera
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.lounge_lamp
          - type: light
            entity: light.bridge
            name: Book Shelf
         
      - type: custom:card-modder
        card:
          type: picture-elements
          title: Shiiiiit Nigga
          image: /local/lovelace/background-15.gif
          elements:
            - type: state-icon
              entity: sensor.lounge_sensor_motion
            - type: state-label
              entity: sensor.lounge_sensor_motion
          style:
            border-radius: 20px

      - type: vertical-stack
        cards:
          - type: custom:mini-media-player
            entity: media_player.bravia_tv
            icon: mdi:television
            artwork_border: true
            show_source: full
            hide_volume: false
            hide_controls: false
          - type: custom:mini-media-player
            entity: media_player.lounge_google_home
            icon: mdi:google-home
            artwork: full-cover
            volume_stateless: false
            show_progress: true
            show_source: true
            show_tts: google
          - type: custom:mini-media-player
            entity: media_player.living_room_chromecast
            icon: mdi:cast
            artwork: full-cover
            volume_stateless: false
            show_progress: true
            show_source: true
            show_tts: google
          - type: custom:mini-media-player
            entity: media_player.spotify
            icon: mdi:spotify
            artwork: full-cover
            volume_stateless: false
            show_progress: true
            show_source: true
            show_tts: google
            
            
      - type: picture-entity
        entity: sensor.lounge_sensor_motion
        camera_image: camera.lounge_camera
            
## BEDROOM VIEW ##

  - title: Bedroom
    cards:
      - type: light
        entity: light.bedroom_light
        name: Bedroom
      - type: custom:mini-media-player
        entity: media_player.bedroom_google_home
        icon: mdi:google-home
        artwork: full-cover
        volume_stateless: false
        show_progress: true
        show_source: true
      - type: custom:mini-media-player
        entity: media_player.bedroom_chromecast
        icon: mdi:google-home
        artwork: full-cover
        volume_stateless: false
        show_progress: true
        show_source: true
        
## NETWORK VIEW ##

  - title: Network
    cards:
      
      - type: glance
        title: Network Speeds
        column_width: calc(100% / 3)
        show_name: false
        entities:
          - entity: sensor.speedtest_download
            name: Download
            icon: mdi:download
          - entity: sensor.speedtest_upload
            name: Upload
            icon: mdi:upload
          - entity: sensor.speedtest_ping
            name: Ping
            icon: mdi:speedometer
            hold_action: call-service
            service: sensor.update_speedtest
            
      - type: entities
        entities:
          - entity: sensor.external_ip
            name: External IP
            icon: mdi:ip-network
          - entity: sensor.ipv4_address_eth0
            name: Local IP
            icon: mdi:ip-network
      
      - type: entities
        title: Pi-Hole
        show_header_toggle: true
        entities:
          - entity: binary_sensor.device_tracker_rpi_pihole
            name: Status
          - entity: sensor.pihole_domains_blocked
            name: Total Domains Being Blocked
          - entity: sensor.pihole_dns_queries_today
            name: DNS Queries Today
          - entity: sensor.pihole_ads_blocked_today
            name: Queries Blocked Today
          - entity: sensor.pihole_ads_percentage_blocked_today
            name: Percentage Blocked Today
          - type: divider
          - entity: sensor.pihole_cpu_temp
            name: CPU Temp
            icon: mdi:thermometer
          - entity: sensor.pihole_cpu_usage
            name: CPU Usage
            icon: mdi:memory
          - entity: sensor.pihole_boot_time
            name: Last Booted
            icon: mdi:update
          - entity: sensor.pihole_disk_usage
            name: Disk Usage
            icon: mdi:micro-sd
          - type: divider
          - type: weblink
            name: Pi-Hole
            url: http://pi.hole/admin
            icon: mdi:raspberrypi
          - type: divider
          - type: weblink
            name: Sky Hub
            url: http://192.168.0.1
            icon: mdi:router-wireless
            
      - type: entities
        title: Device Status
        show_header_toggle: true
        entities:
          - entity: binary_sensor.device_tracker_sony_braviatv
            name: Lounge Sony TV
          - entity: binary_sensor.device_tracker_skyhd
            name: Sky+
            icon: mdi: satellite-uplink
          - entity: binary_sensor.device_tracker_chromecast_lounge
            name: Lounge Chromecast
          - entity: binary_sensor.device_tracker_google_home_lounge
            name: Lounge Google Home
          - entity: binary_sensor.device_tracker_xbox_one
            name: Xbox
          - type: divider
          - entity: binary_sensor.device_tracker_chromecast_bedroom
            name: Bedroom Chromecast
          - entity: binary_sensor.device_tracker_google_home_bedroom
            name: Bedroom Google Home
          - type: divider
          - entity: binary_sensor.device_tracker_milight_bridge
            name: Mi-Light
          - entity: binary_sensor.device_tracker_rich_laptop
            name: Rich Laptop
          - entity: binary_sensor.device_tracker_gear_watch
            name: Rich S2 Watch
          - entity: binary_sensor.device_tracker_lenovo_tab
            name: Rich Tablet
          - type: divider
          - entity: binary_sensor.connectivity_sensor_node_lounge
            name: Lounge Sensor Node
          - entity: binary_sensor.connectivity_sensor_node_bedroom
            name: Bedroom Sensor Node
           

## SYSTEM VIEW ##

  - title: System
    cards:
      - type: entities
        title: System
        show_header_toggle: true
        entities:
          - entity: sensor.ha_time_online
            name: HA Uptime
            icon: mdi:update
          - entity: sensor.hassbian_boot_time
            name: Hassbian Last Boot
            icon: mdi:update
          - entity: sensor.hassbian_cpu_temp
            name: CPU Temperature
            icon: mdi:thermometer
          - entity: sensor.ha_installed_version
            name: HA Version
          - type: divider
          - entity: input_select.theme_changer
            name: Theme select
          - type: divider
          - type: weblink
            name: Home Assistant
            url: https://www.home-assistant.io
            icon: mdi:home-assistant
            
      - type: horizontal-stack
        cards:
          - type: custom:gauge-card
            title: CPU Use
            entity: sensor.processor_use
            min: 0
            max: 100
            severity:
              red: 50
              green: 0
              amber: 40
          
## AUTOMATIONS ##

  - title: Automations
    cards:
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - entity: automation.evening_lights_on
          - entity: automation.motion_lights_lounge_full
          - entity: automation.motion_lights_bedroom_full
          - entity: automation.bedroom_lights_off_after_10
          - entity: automation.lounge_lamp_off_sun_up
          - entity: automation.turn_all_lights_off_at_night
          - entity: automation.turn_all_lights_off_when_away
          
      - type: entities
        title: Presence Detection
        show_header_toggle: true
        entities:
          - entity: automation.presence_detection

      - type: entities
        title: System
        show_header_toggle: true
        entities:
          - entity: automation.ha_update_available
          - entity: automation.home_assistant_started_notify
          - entity: automation.login_failure
          - entity: automation.set_theme
            
      - type: entities
        title: Home Modes
        show_header_toggle: true
        entities:
          - entity: automation.home_mode_home
          - entity: automation.home_mode_away
          - entity: automation.home_mode_morning
          - entity: automation.home_mode_night
          
          
