- platform: limitlessled
  bridges:
    - host: !secret mi-light_ip
      groups:
      - number: 1
        name: Lounge Lamp
        type: rgbw
      - number: 1
        name: Bridge
        type: bridge-led
      - number: 2
        name: Bedroom Light
        type: rgbw
        
