##
- platform: rpi_rf
  gpio: 17
  switches:
    switch_1:
      protocol: 1
      pulselength: 177
      code_on: 12000524
      code_off: 12000516
      signal_repetitions: 44
      
    switch_2:
      protocol: 1
      pulselength: 178
      code_on: 12000522
      code_off: 12000514
      signal_repetitions: 44
      
    tv_backlight_power:
      protocol: 1
      pulselength: 394
      code_on: 2952705 
      code_off: 2952705 
      signal_repetitions: 5
      
    tv_backlight_white:
      protocol: 1
      pulselength: 394
      code_on: 2952718 
      code_off: 2952718 
      signal_repetitions: 10
      
    tv_backlight_red:
      protocol: 1
      pulselength: 393
      code_on: 2952720  
      code_off: 2952720  
      signal_repetitions: 10
      
    tv_backlight_green:
      protocol: 1
      pulselength: 394
      code_on: 2952721
      code_off: 2952721  
      signal_repetitions: 10
      
    tv_backlight_blue:
      protocol: 1
      pulselength: 394
      code_on: 2952722
      code_off: 2952722  
      signal_repetitions: 10
      
    tv_backlight_yellow:
      protocol: 1
      pulselength: 393
      code_on: 2952723
      code_off: 2952723  
      signal_repetitions: 10
      
    tv_backlight_cyan:
      protocol: 1
      pulselength: 395
      code_on: 2952724  
      code_off: 2952724  
      signal_repetitions: 10
      
    tv_backlight_pink:
      protocol: 1
      pulselength: 397
      code_on: 2952725 
      code_off: 2952725  
      signal_repetitions: 10
      
    tv_backlight_brightness_up:
      protocol: 1
      pulselength: 397
      code_on: 2952716 
      code_off: 2952716  
      signal_repetitions: 10
      
    tv_backlight_brightness_down:
      protocol: 1
      pulselength: 394
      code_on: 2952719 
      code_off: 2952719  
      signal_repetitions: 10
