- platform: template
  switches:
    xbox_one:
      value_template: "{{ is_state_attr('remote.harmony_hub_lounge', 'current_activity', 'Play Xbox One') }}"
      turn_on: 
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub_lounge
          activity: 'Play Xbox One'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub_lounge
          activity: 'PowerOff'
          
    watch_tv:
      value_template: "{{ is_state_attr('remote.harmony_hub_lounge', 'current_activity', 'Watch TV') }}"
      turn_on: 
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub_lounge
          activity: 'Watch TV'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub_lounge
          activity: 'PowerOff'
          
    watch_netflix:
      value_template: "{{ is_state_attr('remote.harmony_hub_lounge', 'current_activity', 'Watch Netflix') }}"
      turn_on: 
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub_lounge
          activity: 'Watch Netflix'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub_lounge
          activity: 'PowerOff'