###################################################
## * Special HASS related sensors 
###################################################

- platform: version
  name: HA Installed Version
  scan_interval: 86400

- platform: rest
  resource: https://pypi.python.org/pypi/homeassistant/json
  name: HA Latest Vers.
  value_template: '{{ value_json.info.version }}'
  scan_interval: 86400

#- platform: version
#  name: HA Latest Vers
#  source: pypi

- platform: uptime
  name: HA Time Online
  unit_of_measurement: hours

- platform: filesize
  file_paths:
    - /home/homeassistant/.homeassistant/home-assistant_v2.db
#    - /home/homeassistant/.homeassistant /home-assistant.log
