###################################################
## * Special HASS related sensors 
###################################################

- platform: version
  name: HA Installed Version
  scan_interval: 86400

- platform: rest
  resource: https://pypi.python.org/pypi/homeassistant/json
  name: HA Upstream
  value_template: '{{ value_json.info_version }}'
  scan_interval: 86400

- platform: uptime
  name: Time Online
  unit_of_measurement: hours

#- platform: filesize
#  file_paths:
#    - config/home-assistant_v2.db
#    - config/home-assistant.log

- platform: command_line
  name: "HA Uptime CL"
  command: echo "$(($(date +%s) - $(date -d "$(head -n1 /config/home-assistant.log | cut -d' ' -f-2)" +%s)))"
  scan_interval: 720
  value_template: >-
    {% set uptime = value | int %}
    {% set seconds = uptime % 60 %}
    {% set minutes = ((uptime % 3600) / 60) | int %}
    {% set hours = ((uptime % 86400) / 3600) | int %}
    {% set days = (uptime / 86400) | int %}
    {%- if days > 0 -%}
      {%- if days == 1 -%}
        1 day
      {%- else -%}
        {{ days }} days
      {%- endif -%}
      {{ ', ' }}
    {%- endif -%}
    {%- if hours > 0 -%}
      {%- if hours == 1 -%}
        1 hr
      {%- else -%}
        {{ hours }} hrs
      {%- endif -%}
      {{ ', ' }}
    {%- endif -%}
    {%- if minutes > 0 -%}
      {%- if minutes == 1 -%}
        1 min
      {%- else -%}
        {{ minutes }} mins
      {%- endif -%}
    {%- endif -%}
