- platform: history_stats
  name: TV Watched This Week
  entity_id: media_player.bravia_tv
  state: 'on'
  type: time
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'
  
- platform: history_stats
  name: TV Watched Today
  entity_id: media_player.bravia_tv
  state: 'on'
  type: time
  start: '{{ now().replace(hour=6).replace(minute=0).replace(second=0) }}'
  duration: 
    hours: 18


- platform: history_stats
  name: Xbox This Week
  entity_id: sensor.valiceemo
  state: 'online'
  type: time
  start: '{{ as_timestamp( now().replace(hour=0).replace(minute=0).replace(second=0) ) - now().weekday() * 86400 }}'
  end: '{{ now() }}'
