- platform: mqtt
  state_topic: "sensor-node/master-bedroom"
  name: "Bedroom Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "sensor-node/master-bedroom"
  name: "Bedroom Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "sensor-node/master-bedroom"
  name: 'Bedroom Sensor Motion'
  value_template: '{{ value_json.motion }}'
