- platform: systemmonitor
  resources:
    - type: since_last_boot
    - type: last_boot
    - type: ipv4_address
      arg: eth0
    - type: memory_use_percent
    - type: processor_use
    - type: process
      arg: smbd
#    - type: process
#      arg: mosquitto
    - type: disk_free
      arg: /home
  
- platform: cpuspeed

# platform: mqtt
#  state_topic: 'pi/cpu/temp'
#  name: 'CPU Temp'
#  unit_of_measurement: '°C'
#- platform: mqtt
#  state_topic: 'pi/cpu/fan'
#  name: 'CPU fan'
  

- platform: rest
  scan_interval: 86400
  resource: http://ip.jsontest.com
  name: External IP
  value_template: '{{ value_json.ip }}'


