######################################################################
##  Lounge Lights
######################################################################

- alias: Evening Lights On
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: time
      at: '20:00:00'
  condition:
    - condition: state
      entity_id: device_tracker.rich_phone_s8
      state: 'home'  
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.lounge_lamp
        brightness: 255
        color_name: white
    - service: light.turn_on
      data:
        entity_id:
          - light.bridge
        brightness: 255
        color_name: blue

######################################################################
##  Master Bedroom Lights
######################################################################

- alias: Motion Lights Bedroom Full
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_sonoff_pir
      to: 'Clear'
      from: 'Detected'
  
  condition: 
    - condition: state
      entity_id: device_tracker.rich_phone_s8
      state: 'home'
#    - condition: state
#      entity_id: sun.sun
#      state: 'below_horizon'
  
  action:
    - service: light.turn_on
      data:
        entity_id: 
          - light.bedroom_light
        brightness: 255
        color_name: white
       
######################################################################
##  Turn All Lights Off When Away
######################################################################

- alias: Turn All Lights Off When Away
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      to: 'Away'
      for: '00:05:00'
  condition: 
    condition: or
    conditions:
      - condition: state
        entity_id: light.lounge_lamp
        state: 'on'
      - condition: state
        entity_id: light.bridge
        state: 'on'
      - condition: state
        entity_id: light.bedroom_light
        state: 'on'
  action:

    - service: notify.pushbullet
      data_template:
        title: Home Assistant Lights left on
        message: >
          The following lights are on, I will turn them off...
            {%- for entity_id in states.group.all_lights.attributes.entity_id -%}
            {% set parts = entity_id.split('.') -%}
            {%- if states(entity_id) == 'on' %}
            {%- if loop.first %} {% elif loop.last %} and the {% else %}, the {% endif -%}{{ states[parts[0]][parts[1]].name }}
            {% endif -%}
            {%- endfor %}
        
    - service: script.turn_on
      entity_id: script.all_lights_off
      
#   - service: switch.turn_off
#     entity_id: switch.tv_backlight_power

######################################################################
##  Turn All Lights Off When Returning and It's Dark
######################################################################

- alias: Turn All Lights On When Returning
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      to: 'Home'
  condition: 
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
        
    - service: light.turn_on
      entity_id: group.lounge_lights
      

######################################################################
##  Turn All Lights Off At Night
######################################################################

- alias: Turn All Lights Off At Night
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: time
      at: '00:01:00'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
#    - service: switch.turn_off
#      entity_id: switch.tv_backlight_power
      
######################################################################
##  Motion Lights Lounge
######################################################################

- alias: Motion Lights Lounge Full
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.lounge_sonoff_pir
      to: 'Detected'
      from: 'Clear'
  
  condition: 
    - condition: state
      entity_id: device_tracker.rich_phone_s8
      state: 'home'
    - condition: state
      entity_id: light.lounge_lamp
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.lounge_light_level
      above: 907
  
  action:
    - service: light.turn_on
      data:
        entity_id: 
          - light.lounge_lamp
        brightness: 255
        color_name: white
      
######################################################################
##  Lounge Lamp off Sun Up
######################################################################

- alias: Lounge Lamp Off Sun Up
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.lounge_light_level
      below: 830
  
  condition: 
    - condition: state
      entity_id: device_tracker.rich_phone_s8
      state: 'home'
    - condition: state
      entity_id: light.lounge_lamp
      state: 'on'
#    - condition: state
#      entity_id: sun.sun
#      state: 'above_horizon'
  
  action:
    - service: light.turn_off
      entity_id: light.lounge_lamp
      
######################################################################
##  Master Bedroom Lights out After Delay
######################################################################

- alias: Bedroom Lights off after 10
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_sonoff_pir
      from: 'Detected'
      to: 'Clear'
      for: 
        minutes: 10
        
  condition:
    - condition: state
      entity_id: light.bedroom_light
      state: 'on'
  
  action:
    - service: light.turn_off
      entity_id: light.bedroom_light


      
######################################################################
##  Lounge Lights out After Delay
######################################################################

- alias: Lounge Lamp off after 10
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.lounge_sonoff_pir
      from: 'Detected'
      to: 'Clear'
      for: 
        minutes: 10
        
  condition:
    - condition: state
      entity_id: light.lounge_lamp
      state: 'on'
    - condition: time
      after: '00:00:00'
      before: '06:00:00'
  
  action:
    - service: light.turn_off
      entity_id: light.lounge_lamp

######################################################################
##  TV backlight Off
######################################################################

- alias: TV backlight switch all to off
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: switch.tv_backlight_power
      from: 'on'
      to: 'off'
       
  action:
    - delay: '00:00:15'
    - service: switch.turn_off
      entity_id: group.tv_backlight
