######################################################################
##  Away Mode
######################################################################

- alias: Home Mode Away
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      to: 'Away'
      for: '00:05:00'

  action:
    - service: automation.turn_on
      entity_id: automation.intruder
    - service: automation.turn_off
      entity_id: automation.motion_lights_bedroom_full
    - service: automation.turn_off
      entity_id: automation.bedroom_lights_off_after_10
    - service: light.turn_on
      data:
        entity_id: 
          - light.sensor_node_lounge_led
        brightness: 255
        color_name: green

#####################################################################
##  Home Mode
######################################################################

- alias: Home Mode Home
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: time
      at: '09:01:00'
    - platform: state
      entity_id: input_select.home_mode
      to: 'Home'
      
  action:
    - service: automation.turn_off
      entity_id: automation.intruder
    - service: automation.turn_on
      entity_id: automation.motion_lights_bedroom_full
    - service: automation.turn_on
      entity_id: automation.bedroom_lights_off_after_10
    - service: light.turn_off
      entity_id: light.sensor_node_lounge_led

######################################################################
##  Sleep Mode
######################################################################

- alias: Home Mode Night
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: time
      at: '23:01:00'
    - platform: state
      entity_id: input_select.home_mode
      to: 'Night'
      
  condition:
    - condition: state
      entity_id: device_tracker.rich_phone_s8
      state: 'home'
      
  action:
    - service: automation.turn_off
      entity_id: automation.motion_lights_bedroom_full

######################################################################
##  Morning Mode
######################################################################

- alias: Home Mode Morning
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: time
      at: '08:11:00'
      
  condition:
    - condition: state
      entity_id: device_tracker.rich_s8
      state: 'home'
      
  action:
    - service: input_select.select_option
      entity_id: input_select.home_mode
      data:
        option: 'Home'
