######################################################################
##  Home Assistant Update Available
######################################################################

- alias: HA Update Available
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: time
      at: '05:24:00'
    - platform: homeassistant
      event: start
  condition:
    - condition: template
      value_template: "{{ states('sensor.ha_installed_version') != states('sensor.ha_latest_vers') }}"
  
  action:
    - service: notify.pushbullet
      data:
        title: Update HASS
        message: Home Assistant {{ states('sensor.ha_latest_vers') }} is available. Currently running {{ states('sensor.ha_installed_version') }}
        data:
          url: https://home-assistant.io/blog/
    - service: persistent_notification.create
      data:
        title: "Update Available"
        message: "Home Assistant {{ states('sensor.ha_latest_vers') }} is available. Currently running {{ states('sensor.ha_installed_version') }}"
        notification_id: "update_available"

######################################################################
##  Home Assistant Started
######################################################################

- alias: Home Assistant Started Notify
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.pushbullet
      data:
        title: Home Assistant Ready
        message: Home Assistant has started up to
        
######################################################################
##  Failed Login
######################################################################

- alias: Login Failure
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: template
      value_template: "{{ states('persistent_notification.httplogin') != 'unknown' }}"
  action:
    - service: notify.pushbullet
      data:
        title: Home Assistant
        message: Failed login attempt to your Home Assistant

