######################################################################
##  Arrive at Home
######################################################################

- alias: Presence detection
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: device_tracker.rich_phone_s8
      to: 'home'
      for: '00:05:00'
    - platform: state
      entity_id: device_tracker.rich_phone_s8
      to: 'not_home'

  action:
    - service: input_select.select_option
      entity_id: input_select.home_mode
      data_template:
        option: >
          {% if is_state('device_tracker.rich_phone_s8', 'home') %}
          Home
          {% elif is_state('device_tracker.rich_phone_s8', 'not_home') %}
          Away
          {% endif %}
        
    - service: notify.pushbullet
      data_template:
        title: Home Assistant Presence Monitoring
        message: "{{trigger.entity_id}} changed from {{trigger.from_state.state}} to {{trigger.to_state.state}}"
  
######################################################################
##  Leave Home
######################################################################
