######################################################################
##  Motion Detected !!!
######################################################################

- alias: Intruder
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: sensor.lounge_sensor_motion, sensor.bedroom_sensor_motion
      to: 'motion detected'
      from: 'standby'

  condition:
    - condition: state
      entity_id: input_select.home_mode
      state: 'Away'

  action:
    - service: notify.pushbullet
      data_template:
        title: Home Assistant Alarm
        message: "Motion has been detected by {{ trigger.from_state.attributes.friendly_name }}"

    - service: script.turn_on
      entity_id: script.intruder_detected