######################################################################
##  Away Mode
######################################################################

- alias: Home Mode Away
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      to: 'Away'
      for: '00:05:00'

  action:
    - service: script.turn_on
      entity_id: script.home_mode_away


#####################################################################
##  Home Mode
######################################################################

- alias: Home Mode Home
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      to: 'Home'
      
  action:
    - service: script.turn_on
      entity_id: script.home_mode_home

######################################################################
##  Sleep Mode
######################################################################

- alias: Home Mode Night
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: time
      at: '23:01:00'
    - platform: state
      entity_id: input_select.home_mode
      to: 'Night'
      
  condition:
    - condition: state
      entity_id: device_tracker.rich_phone_s8
      state: 'home'
      
  action:
    - service: script.turn_on
      entity_id: script.home_mode_night

######################################################################
##  Morning Mode weekend
######################################################################

- alias: Home Mode Morning Weekend
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: time
      at: '09:10:00'
      
  condition: 
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.rich_s8
        state: 'home'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'off'
      
  action:
    - service: input_select.select_option
      entity_id: input_select.home_mode
      data:
        option: 'Home'


######################################################################
##  Morning Mode workday
######################################################################

- alias: Home Mode Workday
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: time
      at: '06:32:00'
      
  condition: 
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.rich_s8
        state: 'home'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      
  action:
    - service: input_select.select_option
      entity_id: input_select.home_mode
      data:
        option: 'Home'
