######################################################################
##  Motion Detected !!!
######################################################################

- alias: Intruder
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: sensor.lounge_sensor_node_pir, sensor.bedroom_sensor_node_pir
      to: 'motion detected'
      from: 'standby'

  condition:
    - condition: state
      entity_id: input_select.home_mode
      state: 'Away'

  action:
    - service: notify.pushbullet
      data_template:
        message: >-
          'Movement detected by {{ trigger.from_state.attributes.friendly_name }}'
        title: Intruder at Home!!
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: 'Intruder, your presence has been detected. Fuck Off, the police are on their way!'
    - service: light.turn_on
      data:
        entity_id: 
          - light.lounge_lamp
        brightness: 255
        color_name: red
  
