######################################################################
##  Lounge Lights
######################################################################

- alias: Evening Lights On
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: time
      at: '20:00:00'
  condition:
    - condition: state
      entity_id: device_tracker.rich_s8
      state: 'home'  
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.lounge_lamp
          - light.bridge
        brightness: 255
        color_name: white
    - service: switch.turn_on
      data:
        entity_id:
          - switch.tv_backlight_power
    

######################################################################
##  Master Bedroom Lights
######################################################################

- alias: Motion Lights Bedroom Full
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.bedroom_sensor_node_pir
      to: 'motion detected'
      from: 'standby'
  
  condition: 
    - condition: state
      entity_id: device_tracker.rich_s8
      state: 'home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  
  action:
    - service: light.turn_on
      data:
        entity_id: 
          - light.bedroom_light
        brightness: 255
        color_name: white
       
######################################################################
##  Turn All Lights Off When Away
######################################################################

- alias: Turn All Lights Off When Away
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      to: 'Away'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: switch.tv_backlight_power

######################################################################
##  Turn All Lights Off At Night
######################################################################

- alias: Turn All Lights Off At Night
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: time
      at: '00:01:00'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: switch.tv_backlight_power
      
######################################################################
##  Motion Lights Lounge
######################################################################

- alias: Motion Lights Lounge Full
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.lounge_sensor_node_pir
      to: 'motion detected'
      from: 'standby'
  
  condition: 
    - condition: state
      entity_id: device_tracker.rich_s8
      state: 'home'
    - condition: state
      entity_id: light.lounge_lamp
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.lounge_light_level
      above: 907
  
  action:
    - service: light.turn_on
      data:
        entity_id: 
          - light.lounge_lamp
        brightness: 255
        color_name: white
      
######################################################################
##  Lounge Lamp off
######################################################################

- alias: Lounge Lamp Off - Light on
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.lounge_light_level
      below: 830
  
  condition: 
    - condition: state
      entity_id: device_tracker.rich_s8
      state: 'home'
    - condition: state
      entity_id: light.lounge_lamp
      state: 'on'
  
  action:
    - service: light.turn_off
      entity_id: light.lounge_lamp
      
######################################################################
##  Master Bedroom Lights out After Delay
######################################################################

- alias: Bedroom Lights off after 10
  initial_state: 'on'
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.bedroom_sensor_node_pir
      to: 'standy'
      from: 'motion detected'
      for: 
        minutes: 10
        
  condition:
    - condition: state
      entity_id: light.lounge_lamp
      state: 'on'
  
  action:
    - service: light.turn_off
      entity_id: light.bedroom_light