- platform: plex
  IP_ADDRESS: !secret plex_server_ip
  PORT: !secret plex_server_port
  TOKEN: !secret plex_token
  entity_namespace: plex
  include_non_clients: true
  show_all_controls: true
  use_episode_art: true
